<?php

declare(strict_types=1);

namespace Gubler\UuidTool;

use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;

class UuidTool
{
    public const DEFAULT_CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~.';
    public const FILESYSTEM_CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';


    /**
     * Return a Uuid
     *
     * - If a UUID is provided, will return the UUID,
     * - If a UUID String is provided, will convert to a UUID
     * - If an encoded UUID string (from this class's encode method) is provided, will decode and return UUID
     *
     * @param UuidInterface|string $id
     */
    public static function parse($id, string $charset = self::DEFAULT_CHARSET): UuidInterface
    {
        if ($id instanceof UuidInterface) {
            return $id;
        }

        if (Uuid::isValid($id)) {
            return Uuid::fromString($id);
        }

        return self::decode($id, $charset);
    }

    /**
     * Encode a UUID to a shorter string.
     *
     * The provided $uuid will be parsed before encoding
     *
     * @param UuidInterface|string $uuid
     */
    public static function encode($uuid, string $charset = self::DEFAULT_CHARSET): string
    {
        $source = self::parse($uuid, $charset);

        $number = (string) $source->getInteger();

        $encode = '';

        while (bccomp($number, '0') === 1) {
            $mod = bcmod($number, (string) strlen($charset));
            $encode .= $charset[(int) $mod];
            $number = bcdiv(bcsub($number, $mod), (string) strlen($charset));
        }

        return strrev($encode);
    }

    /**
     * Decode a string generated by UuidTool::encode() back into a UUID.
     *
     * Note that the same charset used to encode the UUID must be used to decode the string.
     */
    public static function decode(string $encodedUuid, string $charset = self::DEFAULT_CHARSET): UuidInterface
    {
        $length = strlen($encodedUuid);
        $array = array_flip(str_split($charset));
        $number = 0;

        for ($i = 0; $i < $length; ++$i) {
            $number = bcadd(
                (string) $number,
                bcmul(
                    (string) $array[$encodedUuid[$i]],
                    bcpow(
                        (string) strlen($charset),
                        (string) ($length - $i - 1)
                    )
                )
            );
        }

        return Uuid::fromInteger($number);
    }
}
